language: c

os:
  - linux

# Only trigger builds on master
branches:
  only:
  - master # Build all commits and PR's on master

# Build matrix
env:
  matrix:
    - APP=test-blinky  TARGET=nucleo
    - APP=test-blinky  TARGET=arm
    - APP=test-blinky  TARGET=science
    - APP=test-blinky  TARGET=safety
    - APP=test-blinky  TARGET=gimbal
    - APP=arm          TARGET=arm
    - APP=science      TARGET=science
    - APP=safety       TARGET=safety
    - APP=gimbal       TARGET=gimbal

# Install tools needed by build
install:
  - wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2 -O /tmp/gcc-arm-none-eabi-8.tar.gz
  - tar -xf /tmp/gcc-arm-none-eabi-8.tar.gz
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-8-2019-q3-update/bin/

# Print toolchain versions
before_script:
  - arm-none-eabi-gcc --version
  - make --version
  - pwd
  - ls -la

# Build with matrix
script:
  - make APP=$APP TARGET=$TARGET -j4

# Log diagnostic info
after_script:
  - du -sh build/$APP/*
  - make clean-all