name: clang-format

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
        with:
          submodules: 'recursive'

      - name: Clang format Check
        uses: DoozyX/clang-format-lint-action@v0.7
        with:
          exclude: './mbed-os'
          clangFormatVersion: 10
